package PrestamoCD_Daniel_Calderon;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daned
 */
public final class FormularioPrestamoCd extends javax.swing.JFrame {


    ArrayList<Cd> listaCd;
    DefaultTableModel modelo;


    public FormularioPrestamoCd() {
        initComponents();
        listaCd = new ArrayList();
        modelo = new DefaultTableModel();
        modelo.addColumn("Titulo Álbum");
        modelo.addColumn("Artista");
        modelo.addColumn("Año");
        modelo.addColumn("Duracion");
        modelo.addColumn("Canciones");
        modelo.addColumn("Prestado");
        mostrarDatos();

    }

    public void mostrarDatos() {
        modelo.setNumRows(listaCd.size());

        for (int i = 0; i < listaCd.size(); i++) {
            modelo.setValueAt(listaCd.get(i).getTitulo(), i, 0);
            modelo.setValueAt(listaCd.get(i).getArtista(), i, 1);
            modelo.setValueAt(listaCd.get(i).getAnioLanzamiento(), i, 2);
            modelo.setValueAt(listaCd.get(i).getDuracion(), i, 3);
            modelo.setValueAt(listaCd.get(i).getNumPistas(), i, 4);
            if (listaCd.get(i).isPrestado() == true) {
                modelo.setValueAt("SI", i, 5);
            } else {
                modelo.setValueAt("NO", i, 5);
            }

        }
        tbl.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_album = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_artista = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_anio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_duracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_num_canciones = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        b_crear_cd = new javax.swing.JButton();
        b_prestar = new javax.swing.JButton();
        b_devolver = new javax.swing.JButton();
        b_eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS PGothic", 1, 18)); // NOI18N
        jLabel1.setText("PRESTAMO DE CD'S DE MÚSICA");

        jLabel2.setText("Titulo del álbum:");

        t_album.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_albumActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre del Artista:");

        t_artista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_artistaActionPerformed(evt);
            }
        });

        jLabel4.setText("Año de lanzamiento:");

        jLabel5.setText("Duracion:");

        jLabel6.setText("Número de canciones:");

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl);

        b_crear_cd.setText("CREAR CD");
        b_crear_cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crear_cdActionPerformed(evt);
            }
        });

        b_prestar.setText("PRESTAR");
        b_prestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_prestarActionPerformed(evt);
            }
        });

        b_devolver.setText("DEVOLVER");
        b_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_devolverActionPerformed(evt);
            }
        });

        b_eliminar.setText("ELIMINAR ALBUM");
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(b_prestar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_devolver)
                .addGap(201, 201, 201)
                .addComponent(b_eliminar)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_album)
                                .addComponent(t_artista, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(t_num_canciones, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_duracion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_anio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(189, 189, 189)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_crear_cd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_artista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(t_num_canciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_crear_cd))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_prestar)
                    .addComponent(b_devolver)
                    .addComponent(b_eliminar))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_albumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_albumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_albumActionPerformed

    private void t_artistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_artistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_artistaActionPerformed

    private void b_crear_cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crear_cdActionPerformed
        // TODO add your handling code here:

        if (!t_album.getText().equals("")
                && !t_artista.getText().equals("")
                && !t_anio.getText().equals("")
                && !t_duracion.getText().equals("") && !t_num_canciones.getText().equals("")) {

            Cd myCd = new Cd(t_artista.getText(), Integer.parseInt(t_num_canciones.getText()), t_album.getText(),
                    Integer.parseInt(t_duracion.getText()), Integer.parseInt(t_anio.getText()));

            listaCd.add(myCd);
            mostrarDatos();
            JOptionPane.showMessageDialog(null, "Cd Creado");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese correctamente todos los datos");
        }

    }//GEN-LAST:event_b_crear_cdActionPerformed

    private void b_prestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_prestarActionPerformed
        // TODO add your handling code here:

        int selectedRow = tbl.getSelectedRow();
        if (selectedRow != -1) {
            if (listaCd.get(selectedRow).isPrestado() == false) {
                listaCd.get(selectedRow).prestar();
                mostrarDatos();
                JOptionPane.showMessageDialog(null, "Cd prestado correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "El CD ya ha sido prestado");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un CD valido");
        }

    }//GEN-LAST:event_b_prestarActionPerformed

    private void b_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_devolverActionPerformed
        // TODO add your handling code here:

        int selectedRow = tbl.getSelectedRow();
        if (selectedRow != -1) {
            if (listaCd.get(selectedRow).isPrestado() == true) {
                listaCd.get(selectedRow).devolver();
                mostrarDatos();
                JOptionPane.showMessageDialog(null, "Cd devuelto correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "El CD ya ha sido devuelto");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un CD valido");
        }

    }//GEN-LAST:event_b_devolverActionPerformed

    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
        // TODO add your handling code here:

        int selectedRow = tbl.getSelectedRow();
        if (selectedRow != -1) {

            if (listaCd.get(selectedRow).isPrestado() == false) {
                listaCd.remove(selectedRow);
            mostrarDatos();
            JOptionPane.showMessageDialog(null, "CD Eliminado");
             

            } else {
                JOptionPane.showMessageDialog(null, "El CD NO se puede elminar por que NO ha sido devuelto");
            }


        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un CD para eliminar");
        }
    }//GEN-LAST:event_b_eliminarActionPerformed

    public void limpiar() {

        t_album.setText("");
        t_anio.setText("");
        t_artista.setText("");
        t_duracion.setText("");
        t_num_canciones.setText("");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrestamoCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrestamoCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrestamoCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrestamoCd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrestamoCd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_crear_cd;
    private javax.swing.JButton b_devolver;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JButton b_prestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_album;
    private javax.swing.JTextField t_anio;
    private javax.swing.JTextField t_artista;
    private javax.swing.JTextField t_duracion;
    private javax.swing.JTextField t_num_canciones;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
